import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import ProgressBar from '@/components/progressbar';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-14 bg-gradient-to-r from-purple-500 to-pink-500">
      <body>
        <Navbar />
        <div className="bg-gradient-to-r from-purple-500 to-pink-500 h-[calc(100vh-5rem)] p-10">
          <ProgressBar />
          <div className="container mx-auto h-full">{children}</div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
